parameters:
    aws_sdk.class: Aws\Sdk

services:
    aws_sdk:
        class: "%aws_sdk.class%"
        arguments:
            - ~
    Aws\Symfony\DependencyInjection\EnvVarProcessor:
        autowire: true
        autoconfigure: true
